services:
  - type: web
    name: diary-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    preDeployCommand: bun run db:migrate:runtime
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_MIGRATE_ON_START
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: diary-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: diary-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: https://diary-lt6c.onrender.com

databases:
  - name: diary-db
    databaseName: diary_db
    user: diary_user
