blank_issues_enabled: false
contact_links:
  - name:
    url: https://github.com/kishimin-ai/diary/discussions
    about: Discussions

# Issue
defaults:
  - template: "bug_report.yml"
    name: " "
    about: ""
  - template: "feature_request.yml"
    name: " "
    about: ""
