name:
description:
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |


  - type: textarea
    id: problem
    attributes:
      label:
      description:
      placeholder:
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label:
      description:
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label:
      description:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label:
      description:
    validations:
      required: false
